### PR TITLE
Added a header image background

### PR DESCRIPTION
**Pull request by sgoyal5**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Added a background image which can be used for multiple screen sizes

### CODE REVIEW

**Comment by sumana2001** [comment]
Hey @sgoyal5! I can't see the change you made in the deploy preview, could you please maybe add a screenshot or something?

**Comment by sgoyal5** [comment]
Dear Ms. Basu,

Attached are the changes that were made. Let me know if you need anything additional.

Sincerely,
Sana Goyal
The University of North Carolina at Chapel Hill
B.S. Computer Science & Statistics, Data Science Minor | May 2025
***@***.*** | (919) 597-9110
________________________________

**Comment by sgoyal5** [comment]
Dear Ms. Basu,

I just wanted to reach out to say that I wasn't able to talk during the meeting today since I woke up with a big fever this morning. My seasonal allergies began flaring up yesterday and I woke up this morning feeling extremely congested and feverish. My partner said that she would be able to show you our changes after the meeting, but I just wanted to reach out to apologize for not responding on the call today. Thank you so much, and please let me know if you need anything additional from me.

Sincerely,
Sana Goyal
The University of North Carolina at Chapel Hill
B.S. Computer Science & Statistics, Data Science Minor | May 2025
***@***.*** | (919) 597-9110
________________________________

**Comment by sumana2001** [comment]
Hey @sgoyal5 I am sorry to hear that, I hope you feel better soon. Don't worry, take rest. Yes, Jenna was able to clear everything up😊

**Comment by sumana2001** [comment]
Screenshot 2023-03-10 at 10 21 15 AM
This photo has a watermark in it. Maybe use a one which doesn't have it?

**Review by sumana2001 — CHANGES_REQUESTED** [review]
Screenshot 2023-03-10 at 10 21 15 AM
This photo has a watermark in it. Maybe use a one which doesn't have it? Otherwise looks great! Loved the idea of including both the tech and racoon😍

**Review by sumana2001 — APPROVED** [review]
Awesome! LGTM

**Pull request merged**
