### PR TITLE
Adding fellow data and changing config.yml

### PR DESCRIPTION
**Pull request by Garvit1809**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by Garvit1809** [comment]
Issue :- #13 
Have added the fellow data received so far and changed the _config.yml file

**Review by sumana2001 — CHANGES_REQUESTED** [review]
Everthing looks great. Only thing to point out is that I am not able to view the social icons in the deployed preview. There should be ideally social media icons on each fellow's card

**Comment by Garvit1809** [comment]
That was another issue so, was gonna make another PR. Should I add in this one only??

**Comment by Garvit1809** [comment]
Hey @sumana2001 , made the fellow cards, tries to add some animations
Issues :- #11 and #13

**Review by sumana2001 — APPROVED** [review]
Amazing job! Looks great💯

**Pull request merged**
